name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Replace API keys
        run: |
          sed -i 's/%%CONSUMER_KEY%%/${{ secrets.CONSUMER_KEY }}/' js/pack.js
          sed -i 's/%%CONSUMER_SECRET%%/${{ secrets.CONSUMER_SECRET }}/' js/pack.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Adjust if you have a different publish directory
