name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Replace API keys
        run: |
          sed -i 's/%%CONSUMER_KEY%%/${{ secrets.CONSUMER_KEY }}/' js/pack.js
          sed -i 's/%%CONSUMER_SECRET%%/${{ secrets.CONSUMER_SECRET }}/' js/pack.js

      - name: Print current directory
        run: pwd

      - name: List files in current directory
        run: ls -la

      - name: List files in js directory
        run: ls -la js/

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create gh-pages branch if not exists
        run: |
          git fetch origin
          if git rev-parse --verify origin/gh-pages; then
            echo "Branch gh-pages exists"
          else
            echo "Creating gh-pages branch"
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initializing gh-pages branch"
            git push origin gh-pages
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./ # Adjust if you have a different publish directory
