name: Merge main to gh-pages

on:
  schedule:
    - cron: '0 0 * * 1' # This runs every Monday at midnight UTC
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout gh-pages branch
        run: git checkout gh-pages

      - name: Merge main into gh-pages with conflict resolution
        run: |
          git merge main --no-edit || true
          if [ $? -ne 0 ]; then
            echo "Merge conflict detected, resolving with main branch version."
            git checkout --theirs js/pack.js
            git add js/pack.js
            git commit -m "Resolved merge conflict by taking main branch version"
          fi
          
      - name: Push changes
        run: git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
